language: python

matrix:
  fast_finish: true
  include:
    - python: '3.5'
      script:
        - poetry run pytest --verbose --cov
        - ./tests/integration.sh
    - python: '3.6'
      script:
        - poetry run pytest --verbose --cov
        - ./tests/integration.sh
    - python: '3.7'
      script:
        - poetry run pytest --verbose --cov
        - ./tests/integration.sh
        - poetry run pre-commit run --all-files --show-diff-on-failure

install:
  - pip install poetry
  - poetry install
